// src/app/portal/page.tsx
import Link from "next/link";
import { Zap, FileText, Mail, Search, MessageSquare } from "lucide-react";

const features = [
  { icon: FileText, label: "Video Scripts & Hooks", description: "TikTok, Reels, Shorts, Facebook" },
  { icon: Zap, label: "Ad Copy", description: "Meta & Google Ads" },
  { icon: Mail, label: "Email Sequences", description: "5-email nurture flows" },
  { icon: Search, label: "SEO Outlines", description: "Keyword-targeted articles" },
  { icon: MessageSquare, label: "Social Captions", description: "Platform-specific posts" },
];

export default function PortalPage() {
  return (
    <main
      className="min-h-screen flex flex-col items-center justify-center px-4 py-16"
      style={{ background: "var(--color-neutral-50)" }}
    >
      <div className="max-w-2xl w-full text-center">
        {/* Logo mark */}
        <div
          className="w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6"
          style={{ background: "var(--color-navy-900)" }}
        >
          <Zap size={28} color="var(--color-blue-400)" />
        </div>

        <p
          className="text-xs font-700 uppercase tracking-widest mb-3"
          style={{ color: "var(--color-blue-500)", fontFamily: "var(--font-body)" }}
        >
          ScaleUpward Client Portal
        </p>

        <h1
          className="text-4xl sm:text-5xl font-800 leading-tight tracking-tight mb-5"
          style={{ color: "var(--color-navy-900)", fontFamily: "var(--font-heading)" }}
        >
          Your AI marketing
          <br />
          engine is ready.
        </h1>

        <p
          className="text-lg leading-relaxed mb-10 max-w-lg mx-auto"
          style={{ color: "var(--color-neutral-500)", fontFamily: "var(--font-body)" }}
        >
          Fill in your brief and get scripts, ads, emails, SEO outlines, and
          captions — all generated by AI in under 60 seconds.
        </p>

        {/* Features */}
        <div className="flex flex-wrap justify-center gap-2 mb-10">
          {features.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.label}
                className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm"
                style={{
                  background: "white",
                  border: "1px solid var(--color-neutral-200)",
                  color: "var(--color-neutral-600)",
                  fontFamily: "var(--font-body)",
                }}
              >
                <Icon size={14} style={{ color: "var(--color-blue-500)" }} />
                {f.label}
              </div>
            );
          })}
        </div>

        <Link
          href="/portal/generate"
          className="inline-flex items-center gap-2 text-white text-base font-600 px-8 py-4 rounded-xl no-underline transition-all hover:-translate-y-0.5"
          style={{
            background: "var(--color-navy-900)",
            fontFamily: "var(--font-body)",
            boxShadow: "0 4px 20px rgba(10,22,40,0.15)",
          }}
        >
          Start Generating
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M3 8h10M8 3l5 5-5 5" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </Link>

        <p
          className="text-xs mt-4"
          style={{ color: "var(--color-neutral-400)", fontFamily: "var(--font-body)" }}
        >
          Takes about 60 seconds to complete
        </p>
      </div>
    </main>
  );
}
